# syntax=docker/dockerfile:1
FROM alpine:3.22

RUN apk add --no-cache ca-certificates curl

COPY scripts/container-bridge-entrypoint.sh /usr/local/bin/jra-van-container-demo
RUN chmod 0755 /usr/local/bin/jra-van-container-demo && mkdir -p /data

VOLUME ["/data"]
ENTRYPOINT ["/usr/local/bin/jra-van-container-demo"]
