/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CatalogBindings src/cloudflare-env.d.ts` (hash: a938bd79b93712927bef378bd9d28e10)
interface __BaseEnv_CatalogBindings {
  CATALOG_KV: KVNamespace;
  CATALOG_OBJECTS: R2Bucket;
  CORNER_VECTORS: VectorizeIndex;
  INGESTION_DLQ_METRICS: Queue;
  INGESTION_ALERTS: Queue;
  R2_SQL_ACCOUNT_ID: string;
  R2_SQL_BUCKET_NAME: string;
  R2_SQL_NAMESPACE: string;
  CACHE_TTL_SECONDS: string;
  KV_TTL_SECONDS: string;
  INGESTION_INBOX: DurableObjectNamespace<import("./vector-gateway").IngestionInbox>;
  INGESTION_ARCHIVE_JOURNAL: DurableObjectNamespace<
    import("./vector-gateway").IngestionArchiveJournal
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./vector-gateway");
    durableNamespaces: "IngestionInbox" | "IngestionArchiveJournal";
  }
  interface Env extends __BaseEnv_CatalogBindings {}
}
interface CatalogBindings extends __BaseEnv_CatalogBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "R2_SQL_ACCOUNT_ID"
      | "R2_SQL_BUCKET_NAME"
      | "R2_SQL_NAMESPACE"
      | "CACHE_TTL_SECONDS"
      | "KV_TTL_SECONDS"
    >
  > {}
}
