"""Records CF-container finish-position serving PROCESSING as data in MLflow.

As of 2026-07-12 the finish-position system is Mac-batch-free: every
prediction is generated by the Cloudflare Container via per-race
"focused-full" runs, triggered by running-style completion or an admin
re-trigger (see `apps/finish-position-cron`). This module answers an
infrastructure-facing question that NEITHER `sync_production.py` (was this
served, and was it accurate) NOR `champion_cell_eval.py`/`cell_eval_runs.py`
(how accurate is the champion) already answers: did the container serve
today's card the way it was designed to -- one race at a time, on schedule,
without partial or duplicate writes, covering the full card -- or is it
exhibiting the failure signatures the pre-CF-only serving-latency audit
already catalogued (batch-fallback bursts, post-time races, partial writes)?

Sources (both READ-ONLY, mirroring this package's existing db.py/serve_eval.py
discipline -- see those modules' own docstrings): the racing Neon database's
`race_finish_position_model_predictions` (via `serve_eval.
fetch_fp_prediction_rows`) for WHAT was actually written and WHEN, and the
local PostgreSQL replica's own jvd_ra/nvd_ra race calendar (via `serve_eval.
fetch_races_scheduled`/`fetch_post_times`) for the expected card and each
race's scheduled post time. No new credential/API surface is introduced: a
Cloudflare D1 REST read (the most literal reading of "D1 realtime_race_
sources" as an expected-card source) would need a `CLOUDFLARE_API_TOKEN`
this repo's env files do not carry today, and jvd_ra/nvd_ra's own
`hasso_jikoku` (post time, "HHMM" text) column is already a genuine, more
authoritative "expected card" oracle -- the same one `serve_eval.
fetch_races_scheduled` already uses for `sync_production.py`'s own
coverage-ratio gap detector -- so this module reuses it instead of adding a
second, narrower data source.

Data model: ONE MLflow run per (date, category) in `config.
EXPERIMENT_FP_CF_SERVING`, identified by a `cf_serving_key = "{date}:
{category}"` tag (mirrors `sync_production.SYNC_KEY_TAG`'s own idiom).
Idempotent by UPDATE-IN-PLACE, not by skip-if-exists: this recorder is
explicitly meant to be re-run many times during race hours (see the
`--partial-coverage-threshold`-style monitoring-sibling use case this was
built for), and each call's per-race table and metrics must REPLACE the
previous snapshot, reflecting the container's progress since the last call --
never accumulate duplicate rows the way a naive re-run of an
exactly-once-per-run table logger would. See `_log_race_table`'s own
docstring for the mechanical consequence of this choice (plain overwriting
artifacts, never `client.log_table`'s special JSON-merge semantics).

The per-race table carries one row per (race, model_version) group actually
served that day: `champion_match` (champion / cell-routed variant / other,
via the SAME duplicated classification rule `sync_production.
_classify_served_model_version` already uses -- see that function's own
"Champion-or-variant serving predicate" section for why hand-duplicating this
~10-line rule across sibling modules, rather than importing it, is this
package's established convention), `write_spread_seconds` (max-min
`prediction_generated_at` across the race's own horse rows -- a real,
directly observable partial-write signal, since every horse in one genuine
UPSERT batch shares Postgres's single per-statement `now()` value), and
`rewrite_count` (see `_build_race_rows`'s own docstring for why this is
tracked as a genuine cross-INVOCATION delta against this run's own
previously-logged table, never fabricated from a single snapshot -- a single
UPSERT-keyed snapshot cannot distinguish "written once" from "written twice
and converged to the same final state").

Anomaly counts, all derived purely from `prediction_generated_at` timestamps
plus the post-time oracle (no additional data source): `late_race_count`
(a race's last write landed within 60 minutes of its own post time, or
after it -- the exact "post後着" phenomenon `serving-latency-audit`
documented for the pre-CF-only hybrid), `missing_before_post_count` (a race
with a resolvable post time that has NEVER been served at all, and that
60-minute deadline has already passed as of `now`), `batch_burst_minute_count`
/ `batch_burst_race_count` (the Mac-batch-fallback signature: more than 4
races landing in the same wall-clock minute -- real per-race container runs
take ~27.5 minutes each, so genuine CF serving can never produce this
pattern; only a batch write of many races in one transaction/script run
can), and `partial_write_race_count` (`write_spread_seconds` above threshold).

ROUTING-HONOR CHECK (2026-07-12, team-lead assignment): a SEPARATE question
from "was a cell-routed variant served" (`variant_races` above, which only
classifies an ALREADY-served model_version as champion/variant/other) --
"did the race that cell_routing.json says should be cell-routed actually GET
its routed variant, or did it silently fall back to the category default (or
something else)?" This matters because a variant_pool load failure or a
config/artifact mismatch at container startup could make a routing rule
fire correctly in intent but never actually produce the expected write, and
the existing `variant_races` counter cannot distinguish "no rule matched
today" from "a rule matched but the container failed to honor it" -- both
look like "no variant rows". Motivated by 07-11's ROUTING-MISSING 15/36 (a
now-fixed old-batch-writer artifact, see `variant_ab.md`); this check is the
recurrence-detection insurance policy the postmortem asked for.

For every race with resolvable race-condition columns (kyori/shusso_tosu/
track_code/kyoso_joken_code/grade_code from jvd_ra/nvd_ra) AND a category
that actually has a cell_routing.json block (`predict_lib.cell_router.
CellRouter.has_routing` -- NAR has none today, see the standing NAR-block
precondition in `adoption_package.md` SS3b-ii, so NAR's routing-honor is
always N/A, never a false "0% honored"), the EXPECTED model_version is
recomputed by calling the REAL `predict_lib.cell_router.resolve_variant`
(never a hand-reimplemented copy of the rule-matching logic -- see
`_load_cell_router`'s own docstring for why re-deriving a parallel copy
would risk silently drifting from what CF actually serves, defeating the
whole point of this check) and compared against the SET of model_versions
actually written for that race. `cf_routing_matched_races` (races where an
expectation was computable at all) / `cf_routing_honored_races` (subset
where the expected model_version was actually written) / `cf_routing_
honor_rate` are logged as metrics; a `routing_honor_flag` tag ("true"/
"false", always re-set on every call so it never goes stale after the
underlying issue self-resolves) marks any call where honor rate < 100%, and
`routing_dishonored_races` names the specific races. DETECTION ONLY -- this
module never remediates, retries, or re-triggers anything.
"""

from __future__ import annotations

import argparse
import importlib
import sys
import tempfile
from collections import Counter
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from datetime import UTC, date, datetime, timedelta, timezone
from pathlib import Path
from typing import Final, Literal, Protocol, cast

import pandas as pd
import psycopg2
import pyarrow as pa
import pyarrow.parquet as pq
from mlflow import MlflowClient
from mlflow.entities import Metric
from mlflow.exceptions import MlflowException

from mlflow_tracking import cells, config, db, registry, serve_eval, trace_emit
from mlflow_tracking.logging_api import get_or_create_experiment, log_batch_chunked

CF_SERVING_KEY_TAG: Final[str] = "cf_serving_key"
TASK: Final[registry.Task] = "finish-position"

RACE_TABLE_JSON_ARTIFACT: Final[str] = "race_processing.json"
RACE_TABLE_PARQUET_ARTIFACT: Final[str] = "race_processing.parquet"

# hasso_jikoku is a JRA/NAR wall-clock time with no embedded timezone marker;
# every real race this recorder ever sees runs in Japan, so JST is hardcoded
# rather than threaded as a parameter -- this matches the rest of this
# package's own hardcoded-JST precedent (see serve_eval.py's is_genuine/
# classify_serving_kind, which compare against JVD's own JST-implicit dates).
JST: Final[timezone] = timezone(timedelta(hours=9))

# A minute bucket with STRICTLY MORE than this many races landing in it is a
# batch-fallback burst -- see this module's own docstring for why a genuine
# per-race container run (~27.5 minutes/race) can never produce this shape.
BATCH_BURST_RACE_THRESHOLD: Final[int] = 4
DEFAULT_LATE_LEAD_MINUTES_THRESHOLD: Final[float] = 60.0
DEFAULT_PARTIAL_WRITE_SPREAD_SECONDS: Final[float] = 5.0

_RACE_TABLE_COLUMNS: Final[tuple[str, ...]] = (
    "race_key",
    "keibajo_code",
    "race_bango",
    "model_version",
    "champion_match",
    "horse_count",
    "prediction_generated_at",
    "write_spread_seconds",
    "rewrite_count",
    "post_time",
    "lead_minutes",
    "late_write",
    "expected_model_version",
    "routing_honored",
)

ROUTING_HONOR_FLAG_TAG: Final[str] = "routing_honor_flag"
ROUTING_DISHONORED_RACES_TAG: Final[str] = "routing_dishonored_races"

# apps/finish-position-predict-container/src -- added to sys.path (never
# installed as a formal dependency) so _load_cell_router can import the
# container's OWN predict_lib.cell_router module. See that function's own
# docstring for why this must be the real container module, not a
# hand-reimplemented copy of its rule-matching logic.
_CONTAINER_SRC: Final[Path] = (
    config.REPO_ROOT / "apps" / "finish-position-predict-container" / "src"
)

# mlflow_tracking's own canonical category spelling is "banei" (registry.
# Category / cells.CATEGORY_BANEI); predict_lib.cell_router.py's
# cell_routing.json is keyed by the container's on-disk directory spelling
# "ban-ei" (see registry.DIRECTORY_CATEGORY_ALIASES, which already performs
# the OPPOSITE "ban-ei" -> "banei" normalization for MLflow registry lookups
# elsewhere in this package). This is the reverse mapping, needed only when
# calling INTO the container's own router -- getting this backwards would
# silently make has_routing("banei") always False even though Ban-ei DOES
# have a live grade_code=E rule, turning routing-honor into a false N/A
# rather than a real check.
_CONTAINER_CATEGORY_BY_MLFLOW_CATEGORY: Final[dict[str, str]] = {"banei": "ban-ei"}


def _container_category(category: str) -> str:
    """Map an mlflow_tracking category to the container's own spelling."""
    return _CONTAINER_CATEGORY_BY_MLFLOW_CATEGORY.get(category, category)


class _VariantSpecLike(Protocol):
    @property
    def model_version(self) -> str: ...


class _CategoryRoutingLike(Protocol):
    """Declared via READ-ONLY `@property` (never a plain mutable attribute):
    two independently-declared Protocols with a plain attribute member are
    NOT always mutually assignable under basedpyright's invariance rules for
    mutable Protocol members, even when the attribute's own type is
    structurally identical elsewhere (e.g. the test suite's own hermetic
    router-fixture Protocol) -- properties are covariant, which is all this
    read-only facade ever needs, and resolves that friction on both ends."""

    @property
    def default_variant(self) -> str: ...
    @property
    def variants(self) -> Mapping[str, _VariantSpecLike]: ...


class _CellRouterLike(Protocol):
    """Structural facade over predict_lib.cell_router.CellRouter -- exists so
    this module can call the REAL container router with full static typing
    (no `# pyright: ignore`, no explicit `Any`) despite that module living
    outside this package's own dependency graph. See `_load_cell_router`'s
    docstring for the runtime side of this: the actual returned object is
    accessed through `importlib.import_module` (typed `Any` per typeshed's
    own `ModuleType.__getattr__` stub), so assigning it to this Protocol-typed
    return is always accepted -- pyright never has to verify the real
    `CellRouter` class structurally matches this Protocol.
    """

    def has_routing(self, category: str) -> bool: ...

    def routing_for(self, category: str) -> _CategoryRoutingLike: ...

    def resolve_variant(
        self,
        category: str,
        entries: Sequence[Mapping[str, object]],
        card_max_race_bango: int | None = None,
    ) -> str: ...


def _load_cell_router() -> _CellRouterLike:
    """Load the REAL predict_lib.cell_router.CellRouter for the container's
    own live cell_routing.json.

    Routing-honor recomputation MUST reuse the container's actual
    resolve_variant/all_conditions_match rule-matching, never a parallel
    hand-copy of it -- a second implementation could silently drift from what
    CF actually serves (a new dimension, a changed derivation), which would
    make this check compare against the WRONG expectation and defeat its own
    purpose. `apps/finish-position-predict-container/src` is added to
    `sys.path` idempotently (checked before insert, so a repeated call within
    one process -- e.g. across `record_cf_serving_day` re-runs -- never grows
    `sys.path` unboundedly) and `predict_lib.cell_router` is imported via
    `importlib.import_module`, never a static `from predict_lib import
    cell_router` -- that sibling package is not a declared dependency of this
    one, so a static import would be an unresolved-import error under
    basedpyright/ty's strict settings. The routing config is (re-)read from
    disk on every call (never cached at module scope) so this always reflects
    whatever cell_routing.json is CURRENTLY deployed, including a rule that
    lands mid-day between two recorder re-runs.
    """
    container_src = str(_CONTAINER_SRC)
    if container_src not in sys.path:
        sys.path.insert(0, container_src)
    module = importlib.import_module("predict_lib.cell_router")
    return module.load_cell_router()


# Isolated per (date, category) so one bad pair never aborts the rest of a
# range call -- mirrors sync_production.py's own `_ISOLATED_EXCEPTIONS` tuple
# exactly (ValueError/KeyError/TypeError for malformed row shapes,
# psycopg2.Error for a live query failure, MlflowException for a tracking-
# store failure). Deliberately narrow: anything else (e.g. a genuine
# programming bug) propagates uncaught, same rationale as every sibling
# module in this package.
_ISOLATED_EXCEPTIONS: Final[tuple[type[BaseException], ...]] = (
    ValueError,
    KeyError,
    TypeError,
    psycopg2.Error,
    MlflowException,
)

_ServedMatchKind = Literal["champion", "variant", "other"]


@dataclass
class CfServingDayResult:
    """Outcome for one `record_cf_serving_day` call.

    `run_created` distinguishes a freshly-created run from a reused one for
    the SAME (date, category) -- both are normal outcomes (see this module's
    own docstring on update-in-place idempotency), never an error either way.
    """

    run_id: str
    run_created: bool
    races_expected: int
    races_covered: int
    coverage_pct: float | None
    champion_races: int
    variant_races: int
    other_races: int
    races_with_post_time: int
    late_race_count: int
    missing_before_post_count: int
    batch_burst_minute_count: int
    batch_burst_race_count: int
    partial_write_race_count: int
    first_write: datetime | None
    last_write: datetime | None
    routing_matched_races: int
    routing_honored_races: int
    routing_honor_rate: float | None
    routing_dishonored_race_keys: tuple[str, ...]


@dataclass
class CfServingRecordSummary:
    """Outcome counters for one `record_cf_serving_range` call."""

    pairs_processed: int = 0
    runs_created: int = 0
    runs_reused: int = 0
    results: list[CfServingDayResult] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class _RoutingHonorResult:
    """Race-level routing-honor outcome for one (date, category) call. See
    this module's own docstring, "ROUTING-HONOR CHECK" section, for the full
    rationale. `dishonored_race_keys` is `f"{keibajo_code}:{race_bango}"`
    strings, sorted, for direct use in a tag value."""

    matched_races: int
    honored_races: int
    dishonored_race_keys: tuple[str, ...]

    @property
    def honor_rate(self) -> float | None:
        if self.matched_races == 0:
            return None
        return 100.0 * self.honored_races / self.matched_races


@dataclass(frozen=True)
class _AnomalyCounts:
    late_race_count: int
    missing_before_post_count: int
    batch_burst_minute_count: int
    batch_burst_race_count: int
    partial_write_race_count: int


# ── Champion-or-variant serving predicate ────────────────────────────────────
#
# Hand-duplicated from sync_production._resolve_champion_label /
# _classify_served_model_version, NOT imported -- see that module's own
# "Champion-or-variant serving predicate" section docstring for why this
# package's established convention is to duplicate this ~15-line rule per
# sibling module rather than share a function reference (built independently,
# zero file-ownership overlap; also, sync_production.py is foreign WIP as of
# this module's own creation and must not be edited to expose it).


def _resolve_champion_label(client: MlflowClient, category: str) -> str | None:
    """Return the CURRENT champion finish-position model_version tag value
    for `category`, or None when there is no resolvable champion (mirrors
    `sync_production._resolve_champion_label` exactly, finish-position-only).
    """
    try:
        normalized = registry.normalize_category(category)
        name = registry.registered_model_name(normalized, TASK)
        registered_model = client.get_registered_model(name)
        version = registered_model.aliases.get(registry.CHAMPION_ALIAS)
        if version is None:
            return None
        model_version = client.get_model_version(name, str(version))
        return model_version.tags.get("model_version")
    except MlflowException:
        return None


def _classify_served_model_version(
    served_model_version: str, champion_label: str | None
) -> _ServedMatchKind:
    """Classify one served `model_version` against the resolved champion
    label -- "champion" (exact match), "variant" (cell-routed, i.e. prefixed
    `f"{champion_label}-"`), or "other" (mirrors `sync_production.
    _classify_served_model_version` exactly)."""
    if champion_label is None:
        return "other"
    if served_model_version == champion_label:
        return "champion"
    if served_model_version.startswith(f"{champion_label}-"):
        return "variant"
    return "other"


def _category_filtered_rows(
    category: str, genuine_rows: list[dict[str, object]]
) -> list[dict[str, object]]:
    """Apply the Ban-ei partition to already-genuine-filtered rows (mirrors
    `sync_production._fp_category_filtered_rows` exactly)."""
    if category == cells.CATEGORY_JRA:
        return genuine_rows
    non_banei_rows, banei_rows = serve_eval.partition_by_banei(genuine_rows)
    return banei_rows if category == cells.CATEGORY_BANEI else non_banei_rows


def _date_range_yyyymmdd(date_from: str, date_to: str) -> list[str]:
    """Every YYYYMMDD string from `date_from` to `date_to`, inclusive (a
    local copy of `sync_production._date_range_yyyymmdd`, same rationale for
    duplication as elsewhere in this module)."""
    start = date(int(date_from[:4]), int(date_from[4:6]), int(date_from[6:8]))
    end = date(int(date_to[:4]), int(date_to[4:6]), int(date_to[6:8]))
    dates: list[str] = []
    current = start
    while current <= end:
        dates.append(current.strftime("%Y%m%d"))
        current += timedelta(days=1)
    return dates


def _parse_hhmm(value: str) -> tuple[int, int] | None:
    """Parse a raw JVD `hasso_jikoku` 4-digit "HHMM" string into (hour,
    minute), or None if it is not a well-formed time -- never raises."""
    if len(value) != 4 or not value.isdigit():
        return None
    hour, minute = int(value[:2]), int(value[2:])
    if not (0 <= hour < 24 and 0 <= minute < 60):
        return None
    return hour, minute


def _post_datetime(date_str: str, hasso_jikoku: str) -> datetime | None:
    """Combine a race's YYYYMMDD date with its "HHMM" post time into a JST
    tz-aware datetime, or None when `hasso_jikoku` does not parse."""
    parsed = _parse_hhmm(hasso_jikoku)
    if parsed is None:
        return None
    hour, minute = parsed
    year, month, day = int(date_str[:4]), int(date_str[4:6]), int(date_str[6:8])
    return datetime(year, month, day, hour, minute, tzinfo=JST)


def _group_by_race_and_model(
    rows: Sequence[Mapping[str, object]],
) -> dict[tuple[str, str, str], list[dict[str, object]]]:
    """Group already-filtered prediction rows by (keibajo_code, race_bango,
    model_version), preserving encounter order."""
    groups: dict[tuple[str, str, str], list[dict[str, object]]] = {}
    for row in rows:
        key = (str(row["keibajo_code"]), str(row["race_bango"]), str(row["model_version"]))
        groups.setdefault(key, []).append(dict(row))
    return groups


def _load_previous_race_table(client: MlflowClient, run_id: str) -> pd.DataFrame | None:
    """Best-effort read-back of `run_id`'s own previously-logged per-race
    table, used ONLY to carry forward `rewrite_count` across re-runs (see
    `_build_race_rows`'s own docstring). Returns None whenever no prior table
    exists yet (a freshly-created run) or the download/parse fails for any
    reason -- never raises: a missing/unreadable prior snapshot only
    degrades every race's `rewrite_count` back to 0 for this call, it never
    blocks recording today's state.
    """
    try:
        local_path = client.download_artifacts(run_id, RACE_TABLE_PARQUET_ARTIFACT)
    except (MlflowException, OSError):
        return None
    try:
        return pd.read_parquet(local_path)
    except (OSError, ValueError, ImportError):
        return None


def _previous_write_state(
    previous_table: pd.DataFrame | None,
) -> dict[tuple[str, str], tuple[datetime, int]]:
    """Map `(race_key, model_version) -> (prediction_generated_at,
    rewrite_count)` from a previously-logged race table, or `{}` when there
    is none (or it is empty -- a prior call that covered zero races)."""
    if previous_table is None or previous_table.empty:
        return {}
    result: dict[tuple[str, str], tuple[datetime, int]] = {}
    for _, prev_row in previous_table.iterrows():
        # `pd.Timestamp(...)` accepts a `pd.Timestamp` OR a plain `datetime`
        # (idempotent either way) -- always normalizing to a plain
        # `datetime` via `.to_pydatetime()` here means `_build_race_rows`'s
        # `!=` comparison against a psycopg2-sourced `datetime` never has to
        # special-case which concrete type a round-tripped-through-parquet
        # value happens to be. `to_pydatetime()` is typed `datetime |
        # NaTType` (pandas' generic "could be Not-a-Time" stub) -- this
        # column is never NaT in practice (`_build_race_rows` always writes
        # a real `prediction_generated_at`), so the final `cast` documents
        # that known invariant rather than adding a dead NaT-handling branch.
        generated_at = cast(
            datetime,
            pd.Timestamp(cast(datetime, prev_row["prediction_generated_at"])).to_pydatetime(),
        )
        result[(str(prev_row["race_key"]), str(prev_row["model_version"]))] = (
            generated_at,
            int(cast(int, prev_row["rewrite_count"])),
        )
    return result


def _build_race_rows(
    date_str: str,
    category: str,
    genuine_rows: list[dict[str, object]],
    champion_label: str | None,
    post_times: Mapping[tuple[str, str], str],
    previous_table: pd.DataFrame | None,
    late_lead_minutes_threshold: float,
) -> list[dict[str, object]]:
    """Build one row per (race, model_version) group actually served that
    day. `rewrite_count` is a genuine cross-INVOCATION counter, not a
    fabricated single-snapshot guess: because `race_finish_position_model_
    predictions` is UPSERT-keyed per horse (see `predict_lib/upsert_sql.py`),
    a snapshot read alone cannot distinguish "this race's rows were written
    once" from "written twice and converged to an identical final state" --
    the earlier write is simply gone, overwritten in place. What CAN be
    measured honestly, across repeated calls of THIS recorder (re-run many
    times per day by design, see this module's own docstring), is whether
    this exact (race, model_version)'s `prediction_generated_at` CHANGED
    since the last call: if it did, a rewrite genuinely happened between the
    two calls, so the counter increments; if the recorder has never seen
    this (race, model_version) before, `rewrite_count` starts at 0 (nothing
    observed yet, not "definitely written only once").
    """
    previous_state = _previous_write_state(previous_table)
    groups = _group_by_race_and_model(genuine_rows)
    race_rows: list[dict[str, object]] = []
    for (keibajo_code, race_bango, model_version), group_rows in groups.items():
        timestamps = [cast(datetime, row["prediction_generated_at"]) for row in group_rows]
        last_write = max(timestamps)
        write_spread_seconds = (last_write - min(timestamps)).total_seconds()
        race_key = f"{date_str}:{category}:{keibajo_code}:{race_bango}"

        previous = previous_state.get((race_key, model_version))
        if previous is None:
            rewrite_count = 0
        else:
            prev_last_write, prev_rewrite_count = previous
            rewrite_count = (
                prev_rewrite_count + 1 if prev_last_write != last_write else prev_rewrite_count
            )

        hasso_jikoku = post_times.get((keibajo_code, race_bango))
        post_dt = _post_datetime(date_str, hasso_jikoku) if hasso_jikoku else None
        lead_minutes = (
            (post_dt - last_write).total_seconds() / 60.0 if post_dt is not None else None
        )
        late_write = lead_minutes is not None and lead_minutes < late_lead_minutes_threshold

        race_rows.append(
            {
                "race_key": race_key,
                "keibajo_code": keibajo_code,
                "race_bango": race_bango,
                "model_version": model_version,
                "champion_match": _classify_served_model_version(model_version, champion_label),
                "horse_count": len(group_rows),
                "prediction_generated_at": last_write,
                "write_spread_seconds": write_spread_seconds,
                "rewrite_count": rewrite_count,
                "post_time": hasso_jikoku,
                "lead_minutes": lead_minutes,
                "late_write": late_write,
            }
        )
    return race_rows


_ROUTING_RACE_CONDITION_COLUMNS: Final[tuple[str, ...]] = (
    "keibajo_code",
    "race_bango",
    "kyori",
    "shusso_tosu",
    "track_code",
    "kyoso_joken_code",
    "grade_code",
)

# A dedicated, narrow SELECT rather than reusing serve_eval.fetch_race_
# metadata: that function is shared by cell_eval_runs.py/sync_production.py/
# champion_cell_eval.py with its own pinned column set (kyori/shusso_tosu/
# track_code/kyoso_joken_code only, no grade_code) and its own tests -- widening
# it here would touch a function this module does not own the full blast
# radius of. grade_code is required for the Ban-ei `grade_code=E` rule (see
# cell_routing.json), so this module's own query adds it. Mirrors serve_eval.
# fetch_race_metadata's own comment-marker convention (the FakeLocalCursor
# test harness dispatches on these SQL comment substrings) and resolve_result_
# tables for table selection -- that ~2-line category -> table lookup is a
# trivial, non-business-logic mapping, reused directly rather than duplicated,
# unlike the champion/variant classification predicate above.
_JRA_ROUTING_CONDITIONS_SQL: Final[str] = f"""
    -- fetch_routing_race_conditions: jra
    SELECT {", ".join(_ROUTING_RACE_CONDITION_COLUMNS)} FROM jvd_ra
    WHERE kaisai_nen = %s AND kaisai_tsukihi = %s
"""

_NAR_ROUTING_CONDITIONS_SQL: Final[str] = f"""
    -- fetch_routing_race_conditions: nar/banei
    SELECT {", ".join(_ROUTING_RACE_CONDITION_COLUMNS)} FROM nvd_ra
    WHERE kaisai_nen = %s AND kaisai_tsukihi = %s
"""


def _fetch_routing_race_conditions(
    conn: db.ConnectionLike, category: str, date_str: str
) -> dict[tuple[str, str], dict[str, object]]:
    """Return `{(keibajo_code, race_bango): {raw condition columns}}` for
    every race in the local replica's own race calendar for (category,
    date_str) -- the raw columns `predict_lib.cell_router.resolve_dimension`
    itself reads (`keibajo_code`/`track_code`/`kyori`/`kyoso_joken_code`/
    `grade_code`; `kaisai_tsukihi` is `date_str`'s own suffix, threaded in by
    the caller rather than re-selected here).

    `category="banei"` reads the same `nvd_ra` rows as `category="nar"` and
    filters to Ban-ei's `keibajo_code`, mirroring `serve_eval.fetch_post_
    times`'s own nar/banei table-sharing convention; `category="nar"` filters
    to EXCLUDE it. NO ValueError branch for an unknown category (unlike the
    public serve_eval.fetch_races_scheduled/fetch_post_times this mirrors) --
    this is a PRIVATE helper only ever called from `record_cf_serving_day`
    AFTER that function's own `category not in cells.CATEGORIES` guard has
    already run, so a third category is provably unreachable here; mirrors
    `_category_filtered_rows`'s own plain if/else (no raise) for the exact
    same reason, rather than adding an untestable-from-the-public-surface
    dead branch.
    """
    if category == cells.CATEGORY_JRA:
        cursor = conn.cursor()
        cursor.execute(_JRA_ROUTING_CONDITIONS_SQL, (date_str[:4], date_str[4:]))
        rows = cursor.fetchall()
    else:
        cursor = conn.cursor()
        cursor.execute(_NAR_ROUTING_CONDITIONS_SQL, (date_str[:4], date_str[4:]))
        rows = cursor.fetchall()

    is_banei = category == cells.CATEGORY_BANEI
    result: dict[tuple[str, str], dict[str, object]] = {}
    for raw_row in rows:
        row: dict[str, object] = dict(zip(_ROUTING_RACE_CONDITION_COLUMNS, raw_row, strict=True))
        keibajo_code = str(row["keibajo_code"])
        if (
            category != cells.CATEGORY_JRA
            and (keibajo_code == serve_eval.BANEI_KEIBAJO_CODE) != is_banei
        ):
            continue
        result[(keibajo_code, str(row["race_bango"]))] = row
    return result


def _expected_model_version(
    category: str,
    router: _CellRouterLike,
    conditions: Mapping[str, object],
    date_str: str,
    field_size: int,
) -> str | None:
    """Return the model_version `predict_lib.cell_router.py` would route this
    race to RIGHT NOW, or None when `category` has no cell_routing.json block
    at all (routing-honor is not a meaningful concept for a blockless
    category -- NAR today, see the standing NAR-block precondition in
    `adoption_package.md` SS3b-ii: NAR serves via the iter40 blend + iter12
    fallback in `model_meta`, not through `cell_router` variants).

    `field_size` stands in for `len(entries)` at real serve time (the
    declared-runner count `resolve_variant` uses for the `field_band`
    dimension) -- the caller passes the ACTUAL served horse_count for this
    race rather than jvd_ra/nvd_ra's own `shusso_tosu` column, since the
    latter is the POST-RACE actual-starter count and can differ from the
    predict-time declared count on a late-scratch race (see cell_router.py's
    own `resolve_dimension` docstring on this exact distinction); using the
    real served count is the closest available proxy to what serving itself
    saw. `entries` is built with `field_size` COPIES of one synthetic row
    (every dimension `resolve_dimension` reads is race-level, not
    horse-level, so the copies are interchangeable) rather than a
    single-element list, because `resolve_variant`'s `field_size = len(entries)`
    would otherwise always compute 1, breaking every field_band-gated rule.

    `category` is `_container_category`-mapped BEFORE every call into
    `router` -- the container's own `CellRouter._routing` dict is keyed by
    its on-disk spelling ("ban-ei"), not this package's canonical "banei"
    (see `_container_category`'s own docstring); calling `router.has_routing`
    with the wrong spelling would silently make Ban-ei's routing-honor a
    false, permanent N/A despite it having a live `grade_code=E` rule.
    """
    container_category = _container_category(category)
    if not router.has_routing(container_category):
        return None
    routing = router.routing_for(container_category)
    entry: dict[str, object] = {
        "keibajo_code": conditions.get("keibajo_code"),
        "track_code": conditions.get("track_code"),
        "kyori": conditions.get("kyori"),
        "kaisai_tsukihi": date_str[4:],
        "grade_code": conditions.get("grade_code"),
        "kyoso_joken_code": conditions.get("kyoso_joken_code"),
    }
    entries = [entry] * max(field_size, 1)
    variant_name = router.resolve_variant(container_category, entries)
    variant_spec = routing.variants.get(variant_name)
    return variant_spec.model_version if variant_spec is not None else None


def _annotate_routing_honor(
    race_rows: list[dict[str, object]],
    category: str,
    router: _CellRouterLike,
    race_conditions: Mapping[tuple[str, str], Mapping[str, object]],
    date_str: str,
) -> _RoutingHonorResult:
    """Mutate every row in `race_rows` with `expected_model_version` /
    `routing_honored` (both None when not computable for that race -- no
    routing table for `category`, or no race-condition row found), and
    return the race-level (not row-level) rollup. A race can have MULTIPLE
    rows (a dual-write incident, or a genuine champion+variant pair) --
    `routing_honored` is computed PER ROW (does THIS row's model_version
    match the expectation) while the returned `_RoutingHonorResult` is
    computed PER RACE (did ANY row for this race match), matching this
    module's own "one row per (race, model_version) group" table convention
    while still giving an honest race-level pass/fail rollup.
    """
    per_race_served: dict[tuple[str, str], set[str]] = {}
    per_race_field_size: dict[tuple[str, str], int] = {}
    for row in race_rows:
        race_id = (str(row["keibajo_code"]), str(row["race_bango"]))
        per_race_served.setdefault(race_id, set()).add(str(row["model_version"]))
        horse_count = cast(int, row["horse_count"])
        per_race_field_size[race_id] = max(per_race_field_size.get(race_id, 0), horse_count)

    expected_by_race: dict[tuple[str, str], str | None] = {}
    for race_id in per_race_served:
        conditions = race_conditions.get(race_id)
        if conditions is None:
            expected_by_race[race_id] = None
            continue
        expected_by_race[race_id] = _expected_model_version(
            category, router, conditions, date_str, per_race_field_size[race_id]
        )

    matched = 0
    honored = 0
    dishonored: list[str] = []
    for race_id, expected in expected_by_race.items():
        if expected is None:
            continue
        matched += 1
        if expected in per_race_served[race_id]:
            honored += 1
        else:
            dishonored.append(f"{race_id[0]}:{race_id[1]}")

    for row in race_rows:
        race_id = (str(row["keibajo_code"]), str(row["race_bango"]))
        expected = expected_by_race.get(race_id)
        row["expected_model_version"] = expected
        row["routing_honored"] = None if expected is None else expected == row["model_version"]

    return _RoutingHonorResult(
        matched_races=matched,
        honored_races=honored,
        dishonored_race_keys=tuple(sorted(dishonored)),
    )


def _floor_minute(value: datetime) -> datetime:
    return value.replace(second=0, microsecond=0)


def _compute_anomalies(
    race_rows: list[dict[str, object]],
    post_times: Mapping[tuple[str, str], str],
    date_str: str,
    now: datetime,
    late_lead_minutes_threshold: float,
    partial_write_spread_seconds: float,
) -> _AnomalyCounts:
    """Derive every anomaly count purely from `race_rows`' own timestamps
    plus the post-time oracle -- see this module's own docstring for what
    each count means and why it needs no additional data source."""
    per_race_last_write: dict[tuple[str, str], datetime] = {}
    per_race_max_spread: dict[tuple[str, str], float] = {}
    covered_race_keys: set[tuple[str, str]] = set()
    late_race_keys: set[tuple[str, str]] = set()
    for row in race_rows:
        race_id = (str(row["keibajo_code"]), str(row["race_bango"]))
        covered_race_keys.add(race_id)
        generated_at = cast(datetime, row["prediction_generated_at"])
        if race_id not in per_race_last_write or generated_at > per_race_last_write[race_id]:
            per_race_last_write[race_id] = generated_at
        spread = cast(float, row["write_spread_seconds"])
        per_race_max_spread[race_id] = max(per_race_max_spread.get(race_id, 0.0), spread)
        if row["late_write"]:
            late_race_keys.add(race_id)

    minute_counts: Counter[datetime] = Counter(
        _floor_minute(ts) for ts in per_race_last_write.values()
    )
    burst_minutes = {
        minute for minute, count in minute_counts.items() if count > BATCH_BURST_RACE_THRESHOLD
    }
    batch_burst_race_count = sum(
        1 for ts in per_race_last_write.values() if _floor_minute(ts) in burst_minutes
    )
    partial_write_race_count = sum(
        1 for spread in per_race_max_spread.values() if spread > partial_write_spread_seconds
    )

    missing_before_post_count = 0
    deadline_delta = timedelta(minutes=late_lead_minutes_threshold)
    for race_id, hasso_jikoku in post_times.items():
        if race_id in covered_race_keys:
            continue
        post_dt = _post_datetime(date_str, hasso_jikoku)
        if post_dt is None:
            continue
        if now >= post_dt - deadline_delta:
            missing_before_post_count += 1

    return _AnomalyCounts(
        late_race_count=len(late_race_keys),
        missing_before_post_count=missing_before_post_count,
        batch_burst_minute_count=len(burst_minutes),
        batch_burst_race_count=batch_burst_race_count,
        partial_write_race_count=partial_write_race_count,
    )


def _find_cf_serving_run(client: MlflowClient, experiment_id: str, key: str) -> str | None:
    """Find the run tagged with `key`, mirroring `sync_production.
    _find_sync_run`'s exact tag-search idiom."""
    matches = client.search_runs(
        [experiment_id],
        filter_string=f"tags.{CF_SERVING_KEY_TAG} = '{key}'",
        max_results=1,
    )
    return matches[0].info.run_id if matches else None


def _race_table_dataframe(race_rows: list[dict[str, object]]) -> pd.DataFrame:
    return pd.DataFrame(race_rows, columns=list(_RACE_TABLE_COLUMNS))


def _log_race_table(client: MlflowClient, run_id: str, df: pd.DataFrame) -> None:
    """Log the per-race processing table as OVERWRITING JSON + parquet
    artifacts -- deliberately NOT via `client.log_table` (see `sync_
    production._log_table_and_parquet`'s own docstring for that API's APPEND
    semantics, which would silently duplicate every row on a second call for
    the same run). This recorder is explicitly re-run many times per day
    (see this module's own docstring), so every call must REPLACE the
    previous snapshot; `client.log_artifact` for a local file has plain
    overwrite-by-path semantics (no merge), which both halves below rely on.
    """
    with tempfile.TemporaryDirectory() as tmp_dir:
        json_path = Path(tmp_dir) / RACE_TABLE_JSON_ARTIFACT
        # `DataFrame.to_json` is typed `str | None` (None only when a
        # `path_or_buf` is given, which this call never does) -- `cast` here
        # documents that this call always returns `str`, matching this
        # package's existing precedent for known-safe pandas-stub gaps (e.g.
        # `serve_eval.py`'s own `cast(float, day_metrics["races"])`).
        json_text = cast(str, df.to_json(orient="records", date_format="iso", indent=2))
        json_path.write_text(json_text, encoding="utf-8")
        client.log_artifact(run_id, str(json_path))
        parquet_path = Path(tmp_dir) / RACE_TABLE_PARQUET_ARTIFACT
        pq.write_table(pa.Table.from_pandas(df, preserve_index=False), parquet_path)
        client.log_artifact(run_id, str(parquet_path))


def record_cf_serving_day(
    client: MlflowClient,
    category: str,
    date_str: str,
    *,
    neon_conn: db.ConnectionLike,
    local_conn: db.ConnectionLike,
    now: datetime | None = None,
    late_lead_minutes_threshold: float = DEFAULT_LATE_LEAD_MINUTES_THRESHOLD,
    partial_write_spread_seconds: float = DEFAULT_PARTIAL_WRITE_SPREAD_SECONDS,
    cell_router: _CellRouterLike | None = None,
) -> CfServingDayResult:
    """Record one (date, category) day's CF-container serving processing.

    `cell_router` mirrors `neon_conn`/`local_conn`'s own injection
    convention: omitted (the real production path), it is resolved via
    `_load_cell_router()` (a live cross-package import of the container's
    actual, currently-deployed routing table); a caller may inject a
    controlled fixture instead -- this is how the test suite exercises
    routing-honor scenarios hermetically without depending on the
    ever-changing real cell_routing.json, and without monkeypatching this
    module's own private helper (this file already treats `neon_conn`/
    `local_conn` as the injection seam, not monkeypatching -- `cell_router`
    joins that same convention rather than starting a new one).

    Finds or creates the `cf_serving_key = "{date_str}:{category}"` run in
    `config.EXPERIMENT_FP_CF_SERVING`, computes every metric/table documented
    in this module's own docstring, and logs it -- REPLACING (not
    appending to) whatever this same run held from a previous call. The run
    is left `FINISHED` on success; on an isolated failure (see this module's
    `_ISOLATED_EXCEPTIONS`) it is left `FAILED` (never stuck `RUNNING`
    forever -- see `sync_production.py`'s own module docstring for the real
    2026-07-11 incident, 18 runs stuck RUNNING after an interrupted process,
    that this try/finally deliberately avoids reproducing in new code) and
    the exception is re-raised for the caller to isolate.

    Raises ValueError for an unsupported category, before any DB/MLflow work.
    """
    if category not in cells.CATEGORIES:
        raise ValueError(f"unknown category: {category!r}")
    resolved_now = now if now is not None else datetime.now(UTC)

    experiment_id = get_or_create_experiment(client, config.EXPERIMENT_FP_CF_SERVING)
    key = f"{date_str}:{category}"
    existing_run_id = _find_cf_serving_run(client, experiment_id, key)
    run_created = existing_run_id is None
    if existing_run_id is None:
        run = client.create_run(
            experiment_id,
            run_name=f"{date_str} {category} cf-serving",
            tags={
                CF_SERVING_KEY_TAG: key,
                "category": category,
                "date": date_str,
                "task": TASK,
            },
        )
        run_id = run.info.run_id
        previous_table: pd.DataFrame | None = None
    else:
        run_id = existing_run_id
        previous_table = _load_previous_race_table(client, run_id)

    try:
        source = serve_eval.resolve_source(category)
        raw_rows = serve_eval.fetch_fp_prediction_rows(neon_conn, source, date_str, date_str)
        genuine_rows = _category_filtered_rows(category, serve_eval.filter_genuine_rows(raw_rows))
        races_expected = serve_eval.fetch_races_scheduled(local_conn, category, date_str)
        post_times = serve_eval.fetch_post_times(local_conn, category, date_str)
        champion_label = _resolve_champion_label(client, category)

        race_rows = _build_race_rows(
            date_str,
            category,
            genuine_rows,
            champion_label,
            post_times,
            previous_table,
            late_lead_minutes_threshold,
        )

        router = cell_router if cell_router is not None else _load_cell_router()
        race_conditions = _fetch_routing_race_conditions(local_conn, category, date_str)
        routing_honor = _annotate_routing_honor(
            race_rows, category, router, race_conditions, date_str
        )

        race_ids = {(str(row["keibajo_code"]), str(row["race_bango"])) for row in race_rows}
        races_covered = len(race_ids)
        coverage_pct = 100.0 * races_covered / races_expected if races_expected > 0 else None
        champion_races = len(
            {
                (row["keibajo_code"], row["race_bango"])
                for row in race_rows
                if row["champion_match"] == "champion"
            }
        )
        variant_races = len(
            {
                (row["keibajo_code"], row["race_bango"])
                for row in race_rows
                if row["champion_match"] == "variant"
            }
        )
        other_races = len(
            {
                (row["keibajo_code"], row["race_bango"])
                for row in race_rows
                if row["champion_match"] == "other"
            }
        )

        anomalies = _compute_anomalies(
            race_rows,
            post_times,
            date_str,
            resolved_now,
            late_lead_minutes_threshold,
            partial_write_spread_seconds,
        )

        timestamps = [cast(datetime, row["prediction_generated_at"]) for row in race_rows]
        first_write = min(timestamps) if timestamps else None
        last_write = max(timestamps) if timestamps else None

        _log_race_table(client, run_id, _race_table_dataframe(race_rows))

        metrics = [
            Metric("cf_races_expected", float(races_expected), 0, 0),
            Metric("cf_races_covered", float(races_covered), 0, 0),
            Metric("cf_champion_races", float(champion_races), 0, 0),
            Metric("cf_variant_races", float(variant_races), 0, 0),
            Metric("cf_other_races", float(other_races), 0, 0),
            Metric("cf_races_with_post_time", float(len(post_times)), 0, 0),
            Metric("cf_late_race_count", float(anomalies.late_race_count), 0, 0),
            Metric(
                "cf_missing_before_post_count", float(anomalies.missing_before_post_count), 0, 0
            ),
            Metric("cf_batch_burst_minute_count", float(anomalies.batch_burst_minute_count), 0, 0),
            Metric("cf_batch_burst_race_count", float(anomalies.batch_burst_race_count), 0, 0),
            Metric("cf_partial_write_race_count", float(anomalies.partial_write_race_count), 0, 0),
            Metric("cf_routing_matched_races", float(routing_honor.matched_races), 0, 0),
            Metric("cf_routing_honored_races", float(routing_honor.honored_races), 0, 0),
        ]
        if coverage_pct is not None:
            metrics.append(Metric("cf_coverage_pct", coverage_pct, 0, 0))
        if first_write is not None:
            metrics.append(Metric("cf_first_write_epoch_s", first_write.timestamp(), 0, 0))
        if last_write is not None:
            metrics.append(Metric("cf_last_write_epoch_s", last_write.timestamp(), 0, 0))
        if routing_honor.honor_rate is not None:
            metrics.append(Metric("cf_routing_honor_rate", routing_honor.honor_rate, 0, 0))
        log_batch_chunked(client, run_id, metrics=metrics)
        # Always RE-SET (never only conditionally set-when-true) so a flag
        # from an earlier partial-day call never lingers after the
        # underlying issue self-resolves on a later re-run -- matches this
        # module's own update-in-place idempotency discipline (see this
        # module's docstring). Only set at all when matched_races > 0 --
        # matches how cf_coverage_pct itself is entirely omitted rather than
        # logged as a misleading 0/0 when there is nothing to compare.
        if routing_honor.matched_races > 0:
            client.set_tag(
                run_id,
                ROUTING_HONOR_FLAG_TAG,
                "false" if routing_honor.honored_races < routing_honor.matched_races else "true",
            )
            client.set_tag(
                run_id,
                ROUTING_DISHONORED_RACES_TAG,
                ",".join(routing_honor.dishonored_race_keys),
            )
    except _ISOLATED_EXCEPTIONS:
        client.set_terminated(run_id, status="FAILED")
        raise

    client.set_terminated(run_id, status="FINISHED")
    return CfServingDayResult(
        run_id=run_id,
        run_created=run_created,
        races_expected=races_expected,
        races_covered=races_covered,
        coverage_pct=coverage_pct,
        champion_races=champion_races,
        variant_races=variant_races,
        other_races=other_races,
        races_with_post_time=len(post_times),
        late_race_count=anomalies.late_race_count,
        missing_before_post_count=anomalies.missing_before_post_count,
        batch_burst_minute_count=anomalies.batch_burst_minute_count,
        batch_burst_race_count=anomalies.batch_burst_race_count,
        partial_write_race_count=anomalies.partial_write_race_count,
        first_write=first_write,
        last_write=last_write,
        routing_matched_races=routing_honor.matched_races,
        routing_honored_races=routing_honor.honored_races,
        routing_honor_rate=routing_honor.honor_rate,
        routing_dishonored_race_keys=routing_honor.dishonored_race_keys,
    )


def record_cf_serving_range(
    client: MlflowClient,
    categories: Sequence[str],
    date_from: str,
    date_to: str,
    *,
    neon_connect: Callable[[], db.ConnectionLike] = db.connect_racing_neon,
    local_connect: Callable[[], db.ConnectionLike] = db.connect_local_replica,
    now: datetime | None = None,
) -> CfServingRecordSummary:
    """Walk every (date, category) pair in [date_from, date_to] x categories,
    recording each via `record_cf_serving_day`, isolating one bad pair's
    failure from the rest (see `_ISOLATED_EXCEPTIONS`).

    Opens both connections ONCE for the whole call (mirrors `sync_production_
    range`'s/`eval_champion_cells_for_category`'s own connection-lifecycle
    idiom), closed in `finally` regardless of outcome.

    Wraps the whole call in one `trace_emit.job_trace` landing in `config.
    EXPERIMENT_FP_CF_SERVING` itself -- matching this package's established
    convention (see `trace_emit.py`'s own "JOB-EXECUTION TRACES" docstring
    section: every experiment except the two `production-usage` experiments
    and `internal/smoke-tests` gets exactly this wiring), with one `t.step`
    per (date, category) pair recorded.
    """
    summary = CfServingRecordSummary()
    dates = _date_range_yyyymmdd(date_from, date_to)

    experiment_id = get_or_create_experiment(client, config.EXPERIMENT_FP_CF_SERVING)
    tracing_client = trace_emit.build_tracing_client(client)

    neon_conn = neon_connect()
    local_conn = local_connect()
    try:
        with trace_emit.job_trace(
            tracing_client,
            experiment_id,
            "cf-serving-recorder",
            attributes={
                "categories": ",".join(categories),
                "date_from": date_from,
                "date_to": date_to,
            },
        ) as t:
            for date_str in dates:
                for category in categories:
                    summary.pairs_processed += 1
                    with t.step("record-day", category=category, date=date_str):
                        try:
                            result = record_cf_serving_day(
                                client,
                                category,
                                date_str,
                                neon_conn=neon_conn,
                                local_conn=local_conn,
                                now=now,
                            )
                        except _ISOLATED_EXCEPTIONS as exc:
                            summary.errors.append(f"{date_str}:{category}: {exc}")
                            continue
                    summary.results.append(result)
                    if result.run_created:
                        summary.runs_created += 1
                    else:
                        summary.runs_reused += 1
            t.feedback("runs_created", float(summary.runs_created))
            t.feedback("errors", float(len(summary.errors)))
    finally:
        neon_conn.close()
        local_conn.close()
    return summary


def _summary_lines(summary: CfServingRecordSummary) -> str:
    return (
        f"pairs processed: {summary.pairs_processed}\n"
        f"runs created: {summary.runs_created}\n"
        f"runs reused: {summary.runs_reused}\n"
        f"errors: {len(summary.errors)}"
    )


def main(argv: Sequence[str] | None = None) -> int:
    """CLI entry point: `uv run python -m mlflow_tracking.cf_serving_recorder`.

    Loads apps/mlflow/.env.local (+ the repo-root .env narrow fallback)
    BEFORE constructing any MlflowClient, mirroring `cli.main`'s own
    ordering exactly -- see this package's safe-pattern discipline: skipping
    this silently writes to a dead local sqlite store instead of the real
    Neon-backed one. Prints the RESOLVED tracking URI so a caller can
    immediately tell whether it landed on the real store or an isolated one.
    """
    config.load_dotenv_local()
    config.load_repo_root_env_fallback()
    parser = argparse.ArgumentParser(
        prog="mlflow_tracking.cf_serving_recorder",
        description="Record CF-container finish-position serving processing into MLflow",
    )
    parser.add_argument("--date-from", required=True, help="Start date (YYYYMMDD), inclusive")
    parser.add_argument("--date-to", required=True, help="End date (YYYYMMDD), inclusive")
    parser.add_argument(
        "--categories",
        default="jra,nar,banei",
        help="Comma-separated categories to record (default: jra,nar,banei)",
    )
    args = parser.parse_args(argv)
    categories = tuple(part.strip() for part in args.categories.split(",") if part.strip())

    client = MlflowClient(tracking_uri=config.get_tracking_uri())
    print(f"tracking uri: {client.tracking_uri}")
    summary = record_cf_serving_range(client, categories, args.date_from, args.date_to)
    print(_summary_lines(summary))
    for error in summary.errors:
        print(f"error: {error}", file=sys.stderr)
    return 1 if summary.errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
