-- Supplemental source-keyed race history for overseas horses whose JV identity
-- is absent or placeholder. This table never writes synthetic values into jvd_*.
-- Race names are display attributes, not identity: source labels can change.
create table if not exists oversea_horse_race_history (
  history_id bigint generated by default as identity primary key,
  source text not null,
  source_horse_id text not null,
  source_race_id text,
  race_date date not null,
  venue text not null,
  race_day_sequence smallint not null,
  race_name text not null,
  source_race_url text,
  finish_position smallint,
  finish_position_text text not null,
  jockey_name text not null,
  source_jockey_id text,
  surface text not null,
  distance_metres integer not null,
  going text not null,
  updated_at timestamptz not null default now(),
  constraint oversea_horse_race_history_source_nonempty check (btrim(source) <> ''),
  constraint oversea_horse_race_history_horse_nonempty check (btrim(source_horse_id) <> ''),
  constraint oversea_horse_race_history_race_id_nonempty check (
    source_race_id is null or btrim(source_race_id) <> ''
  ),
  constraint oversea_horse_race_history_sequence_positive check (race_day_sequence >= 1),
  constraint oversea_horse_race_history_name_nonempty check (btrim(race_name) <> ''),
  constraint oversea_horse_race_history_finish_positive check (
    finish_position is null or finish_position >= 1
  ),
  constraint oversea_horse_race_history_finish_text_nonempty check (
    btrim(finish_position_text) <> ''
  ),
  constraint oversea_horse_race_history_jockey_nonempty check (btrim(jockey_name) <> ''),
  constraint oversea_horse_race_history_distance_positive check (distance_metres > 0),
  constraint oversea_horse_race_history_url_http check (
    source_race_url is null or source_race_url ~ '^https?://'
  )
);

-- Prefer the source's stable race ID whenever it exists.
create unique index if not exists oversea_horse_race_history_source_race_uidx
  on oversea_horse_race_history (source, source_horse_id, source_race_id)
  where source_race_id is not null;

-- Older profile rows lack source race IDs. Stable per-horse/day/venue order is
-- the fallback identity; race_name deliberately remains outside the key.
create unique index if not exists oversea_horse_race_history_fallback_uidx
  on oversea_horse_race_history (
    source,
    source_horse_id,
    race_date,
    venue,
    race_day_sequence
  )
  where source_race_id is null;

create index if not exists oversea_horse_race_history_horse_date_idx
  on oversea_horse_race_history (source, source_horse_id, race_date desc);
