-- Root cause: source-native jockey, trainer, and owner results have no JV-safe
-- storage when the person has no JV code or the result is an overseas race.
-- Scope: preserve source-specific recent results without altering JV masters.
-- Source-specific markup remains in an operator-owned, ignored profile.

begin;

create table if not exists oversea_person_race_history (
  history_id bigint generated by default as identity primary key,
  source text not null check (btrim(source) <> ''),
  person_kind text not null check (person_kind in ('jockey', 'trainer', 'owner')),
  source_person_id text not null check (btrim(source_person_id) <> ''),
  source_race_id text not null check (btrim(source_race_id) <> ''),
  race_date date not null,
  venue text not null check (btrim(venue) <> ''),
  race_number text not null,
  race_name text not null check (btrim(race_name) <> ''),
  source_race_url text not null check (source_race_url ~ '^https?://'),
  source_horse_id text check (source_horse_id is null or btrim(source_horse_id) <> ''),
  horse_name text not null check (btrim(horse_name) <> ''),
  finish_position smallint check (finish_position is null or finish_position >= 1),
  finish_position_text text not null check (btrim(finish_position_text) <> ''),
  surface text not null check (btrim(surface) <> ''),
  distance_metres integer not null check (distance_metres > 0),
  going text check (going is null or btrim(going) <> ''),
  updated_at timestamptz not null default now()
);

create unique index if not exists oversea_person_race_history_source_horse_uidx
  on oversea_person_race_history (
    source,
    person_kind,
    source_person_id,
    source_race_id,
    source_horse_id
  )
  where source_horse_id is not null;

-- Some overseas rows publish a horse name without an identity link. Within a
-- source race, horse names are the only available runner identity.
create unique index if not exists oversea_person_race_history_source_name_uidx
  on oversea_person_race_history (
    source,
    person_kind,
    source_person_id,
    source_race_id,
    horse_name
  )
  where source_horse_id is null;

create index if not exists oversea_person_race_history_person_date_idx
  on oversea_person_race_history (source, person_kind, source_person_id, race_date desc);

commit;
