"""pywinauto の本ファイルで利用する API のみを宣言する最小 stub。
runtime は Windows 専用パッケージのため dev (macOS/Linux) では import できないが、
ty / basedpyright が unresolved-import で警告を出すのを抑えるために存在する。

メインスクリプトで使う Protocol は同名 .pyi に集約して export する。
"""

from __future__ import annotations

from typing import Protocol

class UiaRawElement(Protocol):
    """UIA の raw IUIAutomationElement (COM) の本ファイルで触る API。"""

    @property
    def CurrentIsOffscreen(self) -> bool: ...

class ElementInfo(Protocol):
    @property
    def automation_id(self) -> str: ...
    @property
    def process_id(self) -> int: ...
    @property
    def handle(self) -> int: ...
    @property
    def control_type(self) -> str: ...
    @property
    def element(self) -> UiaRawElement: ...

class UiElement(Protocol):
    @property
    def element_info(self) -> ElementInfo: ...
    def click_input(self) -> object: ...
    def is_enabled(self) -> bool: ...
    def exists(self) -> bool: ...
    def window_text(self) -> str: ...
    def descendants(
        self, *, control_type: str = ..., title: str = ...
    ) -> list[UiElement]: ...
    def child_window(
        self,
        *,
        title: str = ...,
        title_re: str = ...,
        control_type: str = ...,
    ) -> UiElement: ...

class UiWindow(UiElement, Protocol):
    def set_focus(self) -> object: ...
    def close(self) -> object: ...
    def wait(self, state: str, timeout: float = ...) -> object: ...

class Application:
    def __init__(self, backend: str = ...) -> None: ...
    def connect(
        self, *, process: int = ..., timeout: float = ..., **kwargs: object
    ) -> Application: ...
    def window(self, **kwargs: object) -> UiWindow: ...
    def windows(self) -> list[UiWindow]: ...

class Desktop:
    def __init__(self, backend: str = ...) -> None: ...
    def windows(self) -> list[UiWindow]: ...
