"""pywinauto の本ファイルで利用する API のみを宣言する最小 stub。
runtime は Windows 専用パッケージのため dev (macOS/Linux) では import できないが、
ty / basedpyright が unresolved-import で警告を出すのを抑えるために存在する。
"""

from typing import Any

class Application:
    def __init__(self, backend: str = ...) -> None: ...
    def connect(self, *, process: int = ..., timeout: float = ..., **kwargs: Any) -> Application: ...
    def window(self, **kwargs: Any) -> Any: ...
    def windows(self) -> list[Any]: ...

class Desktop:
    def __init__(self, backend: str = ...) -> None: ...
    def windows(self) -> list[Any]: ...
