import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { expect, it } from "vitest";

const migration = readFileSync(
  resolve(process.cwd(), "sql/20260815030000_create_oversea_person_race_history.sql"),
  "utf8",
);
const nullableGoingMigration = readFileSync(
  resolve(process.cwd(), "sql/20260815030050_allow_null_oversea_person_going.sql"),
  "utf8",
);

it("stores the three person kinds with a synchronization-safe primary key", () => {
  expect(migration).toMatch(/history_id bigint generated by default as identity primary key/u);
  expect(migration).toMatch(/person_kind in \('jockey', 'trainer', 'owner'\)/u);
  expect(migration).not.toMatch(/^\s*foreign key/gimu);
});

it("deduplicates linked and name-only source runners separately", () => {
  expect(migration).toMatch(/oversea_person_race_history_source_horse_uidx/u);
  expect(migration).toMatch(/where source_horse_id is not null/u);
  expect(migration).toMatch(/oversea_person_race_history_source_name_uidx/u);
  expect(migration).toMatch(/where source_horse_id is null/u);
});

it("preserves unpublished going as null without allowing empty text", () => {
  expect(migration).toMatch(/going text check \(going is null or btrim\(going\) <> ''\)/u);
  expect(nullableGoingMigration).toMatch(/alter column going drop not null/u);
  expect(nullableGoingMigration).toMatch(/check \(going is null or btrim\(going\) <> ''\)/u);
});
