import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { expect, it } from "vitest";

const sql = readFileSync(
  resolve(process.cwd(), "sql/20260815010000_create_oversea_horse_race_history.sql"),
  "utf8",
);

it("keeps display race names outside overseas history identity", () => {
  expect(sql).toContain("history_id bigint generated by default as identity primary key");
  expect(sql).toContain("(source, source_horse_id, source_race_id)");
  expect(sql).toContain("where source_race_id is not null");
  expect(sql).toContain("race_day_sequence");
  expect(sql).toContain("where source_race_id is null");
  expect(sql).not.toMatch(/unique[^;]*race_name/isu);
});

it("preserves source text and nullable numeric finish without touching JV tables", () => {
  expect(sql).toContain("finish_position smallint");
  expect(sql).toContain("finish_position_text text not null");
  expect(sql).toContain("finish_position is null or finish_position >= 1");
  expect(sql).toContain("source_race_url is null or source_race_url ~ '^https?://'");
  expect(sql).not.toMatch(/\b(?:insert|update|delete|truncate|drop)\s+(?:into\s+|from\s+)?jvd_/iu);
});
