import { decode } from "iconv-lite";
import recordLayouts from "./generated/record-layouts.json" with { type: "json" };
import type { Provider, RecordColumn, RecordLayout, RecordRow } from "./types";

const RECORD_TERMINATOR_BYTES = 2;
const TYPE_BYTES = 2;
const IDENTIFIER = /^[a-z][a-z0-9_]*$/;

const isObject = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

const parseColumn = (value: unknown): RecordColumn => {
  if (!isObject(value) || typeof value.name !== "string" || typeof value.width !== "number")
    throw new Error("Invalid generated record column");
  if (!IDENTIFIER.test(value.name) || !Number.isInteger(value.width) || value.width < 1)
    throw new Error("Invalid generated record column value");
  return { name: value.name, width: value.width };
};

const parseStringArray = (value: unknown): readonly string[] => {
  if (!Array.isArray(value) || value.some((entry) => typeof entry !== "string"))
    throw new Error("Invalid generated primary key");
  const result: string[] = [];
  for (const entry of value) {
    if (!IDENTIFIER.test(entry)) throw new Error("Invalid generated primary key column");
    result.push(entry);
  }
  if (result.length === 0) throw new Error("Generated primary key is empty");
  return result;
};

const parseLayout = (tableName: string, value: unknown): RecordLayout => {
  if (!IDENTIFIER.test(tableName) || !isObject(value) || !Array.isArray(value.columns))
    throw new Error("Invalid generated record layout");
  if (typeof value.recordBytes !== "number" || typeof value.recordType !== "string")
    throw new Error("Invalid generated record layout metadata");
  const columns = value.columns.map(parseColumn);
  const primaryKey = parseStringArray(value.primaryKey);
  const bytes = columns.reduce((total, column) => total + column.width, RECORD_TERMINATOR_BYTES);
  if (bytes !== value.recordBytes || !/^[A-Z0-9]{2}$/.test(value.recordType))
    throw new Error(`Invalid generated byte layout for ${tableName}`);
  return {
    columns,
    primaryKey,
    recordBytes: value.recordBytes,
    recordType: value.recordType,
    tableName,
  };
};

export const validateRecordLayouts = (value: unknown): ReadonlyMap<string, RecordLayout> => {
  if (!isObject(value) || value.formatVersion !== 1 || !isObject(value.tables))
    throw new Error("Invalid generated record layouts");
  const layouts = new Map<string, RecordLayout>();
  for (const [tableName, table] of Object.entries(value.tables)) {
    const layout = parseLayout(tableName, table);
    layouts.set(`${tableName.slice(0, 3)}:${layout.recordType}`, layout);
  }
  return layouts;
};

const LAYOUTS = validateRecordLayouts(recordLayouts);

const textCatalogColumns = (names: readonly string[]): RecordColumn[] =>
  names.map((name) => ({ catalogType: "string", name, width: 0 }));

const NETKEIBA_TRAINING_LAYOUT: RecordLayout = {
  columns: [
    ...textCatalogColumns([
      "kaisai_nen",
      "kaisai_tsukihi",
      "keibajo_code",
      "race_bango",
      "source_race_id",
      "umaban",
      "ketto_toroku_bango",
      "workout_key",
      "record_id",
      "data_kubun",
      "data_sakusei_nengappi",
      "tracen_kubun",
      "chokyo_nengappi",
      "chokyo_jikoku",
      "course",
      "babamawari",
      "training_type",
    ]),
    { catalogType: "int", name: "workout_index", width: 0 },
    ...textCatalogColumns([
      "bamei",
      "rider_name",
      "time_gokei_10f",
      "lap_time_10f",
      "time_gokei_9f",
      "lap_time_9f",
      "time_gokei_8f",
      "lap_time_8f",
      "time_gokei_7f",
      "lap_time_7f",
      "time_gokei_6f",
      "lap_time_6f",
      "time_gokei_5f",
      "lap_time_5f",
      "time_gokei_4f",
      "lap_time_4f",
      "time_gokei_3f",
      "lap_time_3f",
      "time_gokei_2f",
      "lap_time_2f",
      "lap_time_1f",
      "evaluation_grade",
      "evaluation_text",
      "comment_text",
      "source_url",
    ]),
    { catalogType: "timestamptz", name: "fetched_at", width: 0 },
    { catalogType: "timestamptz", name: "created_at", width: 0 },
    { catalogType: "timestamptz", name: "updated_at", width: 0 },
  ],
  primaryKey: [
    "kaisai_nen",
    "kaisai_tsukihi",
    "keibajo_code",
    "race_bango",
    "ketto_toroku_bango",
    "workout_key",
  ],
  recordBytes: 0,
  recordType: "NK",
  tableName: "netkeiba_training_workouts",
};

export const optionalLayoutForRecord = (
  provider: Provider,
  bytes: Uint8Array,
): RecordLayout | undefined => {
  if (bytes.length < TYPE_BYTES) throw new Error("Record is shorter than its type prefix");
  const recordType = String.fromCharCode(...bytes.subarray(0, TYPE_BYTES));
  return LAYOUTS.get(`${provider === "jv" ? "jvd" : "nvd"}:${recordType}`);
};

export const layoutForRecord = (provider: Provider, bytes: Uint8Array): RecordLayout => {
  const layout = optionalLayoutForRecord(provider, bytes);
  if (layout === undefined) throw new Error(`Unsupported ${provider.toUpperCase()} record type`);
  return layout;
};

export const parseFixedRecord = (layout: RecordLayout, bytes: Uint8Array): RecordRow => {
  if (bytes.length !== layout.recordBytes)
    throw new Error(`Invalid ${layout.tableName} record length`);
  if (bytes.at(-2) !== 13 || bytes.at(-1) !== 10)
    throw new Error(`Invalid ${layout.tableName} record terminator`);
  const row: Record<string, string> = {};
  let offset = 0;
  for (const column of layout.columns) {
    const end = offset + column.width;
    row[column.name] = decode(bytes.subarray(offset, end), "cp932");
    offset = end;
  }
  return Object.freeze(row);
};

export const rowKey = (layout: RecordLayout, row: RecordRow): string => {
  const values: string[] = [];
  for (const column of layout.primaryKey) {
    const value = row[column];
    if (typeof value !== "string" && typeof value !== "number")
      throw new Error(`Missing primary key column for ${layout.tableName}`);
    values.push(String(value));
  }
  return values.join("\u001f");
};

export const layoutByTable = (tableName: string): RecordLayout => {
  if (tableName === NETKEIBA_TRAINING_LAYOUT.tableName) return NETKEIBA_TRAINING_LAYOUT;
  for (const layout of LAYOUTS.values()) if (layout.tableName === tableName) return layout;
  throw new Error("Unsupported table");
};
