import "server-only";
import {
  boolean,
  date,
  integer,
  numeric,
  pgTable,
  smallint,
  text,
  timestamp,
  varchar,
} from "drizzle-orm/pg-core";

const raceColumns = {
  kaisaiNen: varchar("kaisai_nen", { length: 4 }).notNull(),
  kaisaiTsukihi: varchar("kaisai_tsukihi", { length: 4 }).notNull(),
  keibajoCode: varchar("keibajo_code", { length: 2 }).notNull(),
  kaisaiKai: varchar("kaisai_kai", { length: 2 }),
  kaisaiNichime: varchar("kaisai_nichime", { length: 2 }),
  raceBango: varchar("race_bango", { length: 2 }).notNull(),
  kyosomeiHondai: varchar("kyosomei_hondai", { length: 60 }),
  kyosomeiFukudai: varchar("kyosomei_fukudai", { length: 60 }),
  kyosomeiKakkonai: varchar("kyosomei_kakkonai", { length: 60 }),
  gradeCode: varchar("grade_code", { length: 1 }),
  kyosoShubetsuCode: varchar("kyoso_shubetsu_code", { length: 2 }),
  kyosoKigoCode: varchar("kyoso_kigo_code", { length: 3 }),
  juryoShubetsuCode: varchar("juryo_shubetsu_code", { length: 1 }),
  kyosoJokenCode: varchar("kyoso_joken_code", { length: 3 }),
  kyosoJokenMeisho: varchar("kyoso_joken_meisho", { length: 60 }),
  kyori: varchar("kyori", { length: 4 }),
  trackCode: varchar("track_code", { length: 2 }),
  hassoJikoku: varchar("hasso_jikoku", { length: 4 }),
  torokuTosu: varchar("toroku_tosu", { length: 2 }),
  shussoTosu: varchar("shusso_tosu", { length: 2 }),
  tenkoCode: varchar("tenko_code", { length: 1 }),
  babajotaiCodeShiba: varchar("babajotai_code_shiba", { length: 1 }),
  babajotaiCodeDirt: varchar("babajotai_code_dirt", { length: 1 }),
};

const runnerColumns = {
  kaisaiNen: varchar("kaisai_nen", { length: 4 }).notNull(),
  kaisaiTsukihi: varchar("kaisai_tsukihi", { length: 4 }).notNull(),
  keibajoCode: varchar("keibajo_code", { length: 2 }).notNull(),
  raceBango: varchar("race_bango", { length: 2 }).notNull(),
  wakuban: varchar("wakuban", { length: 1 }),
  umaban: varchar("umaban", { length: 2 }),
  kettoTorokuBango: varchar("ketto_toroku_bango", { length: 10 }),
  bamei: varchar("bamei", { length: 36 }),
  moshokuCode: varchar("moshoku_code", { length: 2 }),
  seibetsuCode: varchar("seibetsu_code", { length: 1 }),
  barei: varchar("barei", { length: 2 }),
  futanJuryo: varchar("futan_juryo", { length: 3 }),
  kishumeiRyakusho: varchar("kishumei_ryakusho", { length: 8 }),
  chokyoshimeiRyakusho: varchar("chokyoshimei_ryakusho", { length: 8 }),
  banushimei: varchar("banushimei", { length: 64 }),
  bataiju: varchar("bataiju", { length: 3 }),
  zogenFugo: varchar("zogen_fugo", { length: 1 }),
  zogenSa: varchar("zogen_sa", { length: 3 }),
  kakuteiChakujun: varchar("kakutei_chakujun", { length: 2 }),
  tanshoOdds: varchar("tansho_odds", { length: 4 }),
  tanshoNinkijun: varchar("tansho_ninkijun", { length: 2 }),
  sohaTime: varchar("soha_time", { length: 4 }),
  timeSa: varchar("time_sa", { length: 4 }),
  corner1: varchar("corner_1", { length: 2 }),
  corner2: varchar("corner_2", { length: 2 }),
  corner3: varchar("corner_3", { length: 2 }),
  corner4: varchar("corner_4", { length: 2 }),
  kohan3f: varchar("kohan_3f", { length: 3 }),
};

const horseMasterColumns = {
  kettoTorokuBango: varchar("ketto_toroku_bango", { length: 10 }).notNull(),
  bamei: varchar("bamei", { length: 36 }),
  sireName: varchar("ketto_joho_01b", { length: 36 }),
  damName: varchar("ketto_joho_02b", { length: 36 }),
  sireSireName: varchar("ketto_joho_03b", { length: 36 }),
  damSireName: varchar("ketto_joho_05b", { length: 36 }),
};

export const jvdCs = pgTable("jvd_cs", {
  keibajoCode: varchar("keibajo_code", { length: 2 }).notNull(),
  kyori: varchar("kyori", { length: 4 }).notNull(),
  trackCode: varchar("track_code", { length: 2 }).notNull(),
  courseKaishuNengappi: varchar("course_kaishu_nengappi", { length: 8 }).notNull(),
  courseSetsumei: varchar("course_setsumei", { length: 6800 }),
});

export const jvdRa = pgTable("jvd_ra", raceColumns);
export const nvdRa = pgTable("nvd_ra", raceColumns);
export const jvdSe = pgTable("jvd_se", runnerColumns);
export const nvdSe = pgTable("nvd_se", runnerColumns);
export const jvdUm = pgTable("jvd_um", horseMasterColumns);
export const nvdNu = pgTable("nvd_nu", horseMasterColumns);
export const nvdUm = pgTable("nvd_um", horseMasterColumns);

export const overseaHorsePedigree = pgTable("oversea_horse_pedigree", {
  source: text("source").notNull(),
  sourceHorseId: text("source_horse_id").notNull(),
  sireSourceId: text("sire_source_id"),
  sireName: text("sire_name").notNull(),
  sireSireSourceId: text("sire_sire_source_id"),
  sireSireName: text("sire_sire_name").notNull(),
  damSourceId: text("dam_source_id"),
  damName: text("dam_name").notNull(),
  damSireSourceId: text("dam_sire_source_id"),
  damSireName: text("dam_sire_name").notNull(),
  sourceUrl: text("source_url").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export const overseaHorseRaceHistory = pgTable("oversea_horse_race_history", {
  source: text("source").notNull(),
  sourceHorseId: text("source_horse_id").notNull(),
  sourceRaceId: text("source_race_id"),
  raceDate: date("race_date").notNull(),
  venue: text("venue").notNull(),
  raceDaySequence: smallint("race_day_sequence").notNull(),
  raceName: text("race_name").notNull(),
  sourceRaceUrl: text("source_race_url"),
  finishPosition: smallint("finish_position"),
  finishPositionText: text("finish_position_text").notNull(),
  jockeyName: text("jockey_name").notNull(),
  sourceJockeyId: text("source_jockey_id"),
  surface: text("surface").notNull(),
  distanceMetres: integer("distance_metres").notNull(),
  going: text("going").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export const overseaPersonWinRateStats = pgTable("oversea_person_win_rate_stats", {
  raceSource: text("race_source").notNull(),
  kaisaiNen: text("kaisai_nen").notNull(),
  kaisaiTsukihi: text("kaisai_tsukihi").notNull(),
  keibajoCode: text("keibajo_code").notNull(),
  raceBango: text("race_bango").notNull(),
  category: text("category").notNull(),
  name: text("name").notNull(),
  currentHorseNumbers: text("current_horse_numbers").notNull(),
  statsSource: text("stats_source").notNull(),
  scope: text("scope").notNull(),
  years: smallint("years"),
  minimumStarts: smallint("minimum_starts").notNull(),
  calculatedThrough: date("calculated_through").notNull(),
  calculatedAt: timestamp("calculated_at", { withTimezone: true }).notNull(),
  sourcePersonId: text("source_person_id"),
  populationStart: date("population_start"),
  populationEnd: date("population_end"),
  publishedPopulationSize: integer("published_population_size"),
  populationComplete: boolean("population_complete").notNull(),
  starts: integer("starts").notNull(),
  horseCount: integer("horse_count").notNull(),
  winCount: integer("win_count").notNull(),
  quinellaCount: integer("quinella_count").notNull(),
  showCount: integer("show_count").notNull(),
  winRate: numeric("win_rate", { precision: 5, scale: 1 }).notNull(),
  quinellaRate: numeric("quinella_rate", { precision: 5, scale: 1 }).notNull(),
  showRate: numeric("show_rate", { precision: 5, scale: 1 }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export const overseaPersonRaceHistory = pgTable("oversea_person_race_history", {
  source: text("source").notNull(),
  personKind: text("person_kind").notNull(),
  sourcePersonId: text("source_person_id").notNull(),
  sourceRaceId: text("source_race_id").notNull(),
  raceDate: date("race_date").notNull(),
  venue: text("venue"),
  raceNumber: text("race_number").notNull(),
  raceName: text("race_name").notNull(),
  sourceRaceUrl: text("source_race_url").notNull(),
  sourceHorseId: text("source_horse_id"),
  horseName: text("horse_name"),
  finishPosition: smallint("finish_position"),
  finishPositionText: text("finish_position_text").notNull(),
  surface: text("surface"),
  distanceMetres: integer("distance_metres"),
  going: text("going"),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export const overseaRunnerSourceId = pgTable("oversea_runner_source_id", {
  raceSource: text("race_source").notNull(),
  kaisaiNen: text("kaisai_nen").notNull(),
  kaisaiTsukihi: text("kaisai_tsukihi").notNull(),
  keibajoCode: text("keibajo_code").notNull(),
  raceBango: text("race_bango").notNull(),
  umaban: text("umaban").notNull(),
  source: text("source").notNull(),
  sourceHorseId: text("source_horse_id").notNull(),
  sourceJockeyId: text("source_jockey_id"),
  sourceTrainerId: text("source_trainer_id"),
  sourceOwnerId: text("source_owner_id"),
  gateNumber: smallint("gate_number"),
  sourceUrl: text("source_url"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export const overseaRunnerIdentity = pgTable("oversea_runner_identity", {
  raceSource: text("race_source").notNull(),
  kaisaiNen: text("kaisai_nen").notNull(),
  kaisaiTsukihi: text("kaisai_tsukihi").notNull(),
  keibajoCode: text("keibajo_code").notNull(),
  raceBango: text("race_bango").notNull(),
  umaban: text("umaban").notNull(),
  source: text("source").notNull(),
  sourceHorseId: text("source_horse_id").notNull(),
  horseNameFull: text("horse_name_full").notNull(),
  jockeyNameFull: text("jockey_name_full"),
  trainerNameFull: text("trainer_name_full"),
  ownerNameFull: text("owner_name_full"),
  sourceUrl: text("source_url"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});
