// Run with bun (bunx vitest).

import { expect, it } from "vitest";

import type { Training } from "../../../lib/race-types";
import { mergePremiumTrainingReviews } from "./premium-training-merge";

it("returns trainings unchanged when reviews are empty", () => {
  const trainings: Training[] = [
    {
      babamawari: null,
      bamei: "alpha",
      chokyoJikoku: "0500",
      chokyoNengappi: "20260620",
      course: null,
      lapTime10f: null,
      lapTime1f: null,
      lapTime2f: null,
      lapTime3f: null,
      lapTime4f: null,
      lapTime5f: null,
      lapTime6f: null,
      lapTime7f: null,
      lapTime8f: null,
      lapTime9f: null,
      timeGokei10f: null,
      timeGokei2f: null,
      timeGokei3f: null,
      timeGokei4f: null,
      timeGokei5f: null,
      timeGokei6f: null,
      timeGokei7f: null,
      timeGokei8f: null,
      timeGokei9f: null,
      tracenKubun: null,
      trainingType: "通常",
      umaban: "5",
    },
  ];
  const result = mergePremiumTrainingReviews(trainings, []);
  expect(result).toStrictEqual([
    {
      babamawari: null,
      bamei: "alpha",
      chokyoJikoku: "0500",
      chokyoNengappi: "20260620",
      course: null,
      lapTime10f: null,
      lapTime1f: null,
      lapTime2f: null,
      lapTime3f: null,
      lapTime4f: null,
      lapTime5f: null,
      lapTime6f: null,
      lapTime7f: null,
      lapTime8f: null,
      lapTime9f: null,
      timeGokei10f: null,
      timeGokei2f: null,
      timeGokei3f: null,
      timeGokei4f: null,
      timeGokei5f: null,
      timeGokei6f: null,
      timeGokei7f: null,
      timeGokei8f: null,
      timeGokei9f: null,
      tracenKubun: null,
      trainingType: "通常",
      umaban: "5",
    },
  ]);
});

it("attaches a review to the matching row when horse number and date both match", () => {
  const result = mergePremiumTrainingReviews(
    [
      {
        babamawari: null,
        bamei: "alpha",
        chokyoJikoku: "0500",
        chokyoNengappi: "20260615",
        course: null,
        lapTime10f: null,
        lapTime1f: null,
        lapTime2f: null,
        lapTime3f: null,
        lapTime4f: null,
        lapTime5f: null,
        lapTime6f: null,
        lapTime7f: null,
        lapTime8f: null,
        lapTime9f: null,
        timeGokei10f: null,
        timeGokei2f: null,
        timeGokei3f: null,
        timeGokei4f: null,
        timeGokei5f: null,
        timeGokei6f: null,
        timeGokei7f: null,
        timeGokei8f: null,
        timeGokei9f: null,
        tracenKubun: null,
        trainingType: "通常",
        umaban: "5",
      },
      {
        babamawari: null,
        bamei: "alpha",
        chokyoJikoku: "0500",
        chokyoNengappi: "20260620",
        course: null,
        lapTime10f: null,
        lapTime1f: null,
        lapTime2f: null,
        lapTime3f: null,
        lapTime4f: null,
        lapTime5f: null,
        lapTime6f: null,
        lapTime7f: null,
        lapTime8f: null,
        lapTime9f: null,
        timeGokei10f: null,
        timeGokei2f: null,
        timeGokei3f: null,
        timeGokei4f: null,
        timeGokei5f: null,
        timeGokei6f: null,
        timeGokei7f: null,
        timeGokei8f: null,
        timeGokei9f: null,
        tracenKubun: null,
        trainingType: "通常",
        umaban: "5",
      },
    ],
    [
      {
        commentText: "comment-a",
        evaluationGrade: "B",
        evaluationText: "目立たず",
        horseNumber: "5",
        riderName: null,
        trainingDate: "2026/06/15",
      },
    ],
  );
  expect(result).toStrictEqual([
    {
      babamawari: null,
      bamei: "alpha",
      chokyoJikoku: "0500",
      chokyoNengappi: "20260615",
      course: null,
      lapTime10f: null,
      lapTime1f: null,
      lapTime2f: null,
      lapTime3f: null,
      lapTime4f: null,
      lapTime5f: null,
      lapTime6f: null,
      lapTime7f: null,
      lapTime8f: null,
      lapTime9f: null,
      premiumCommentText: "comment-a",
      premiumEvaluationGrade: "B",
      premiumEvaluationText: "目立たず",
      timeGokei10f: null,
      timeGokei2f: null,
      timeGokei3f: null,
      timeGokei4f: null,
      timeGokei5f: null,
      timeGokei6f: null,
      timeGokei7f: null,
      timeGokei8f: null,
      timeGokei9f: null,
      tracenKubun: null,
      trainingRiderName: undefined,
      trainingType: "通常",
      umaban: "5",
    },
    {
      babamawari: null,
      bamei: "alpha",
      chokyoJikoku: "0500",
      chokyoNengappi: "20260620",
      course: null,
      lapTime10f: null,
      lapTime1f: null,
      lapTime2f: null,
      lapTime3f: null,
      lapTime4f: null,
      lapTime5f: null,
      lapTime6f: null,
      lapTime7f: null,
      lapTime8f: null,
      lapTime9f: null,
      timeGokei10f: null,
      timeGokei2f: null,
      timeGokei3f: null,
      timeGokei4f: null,
      timeGokei5f: null,
      timeGokei6f: null,
      timeGokei7f: null,
      timeGokei8f: null,
      timeGokei9f: null,
      tracenKubun: null,
      trainingType: "通常",
      umaban: "5",
    },
  ]);
});

it("attaches a dateless review to a row by horse number alone", () => {
  const result = mergePremiumTrainingReviews(
    [
      {
        babamawari: null,
        bamei: "alpha",
        chokyoJikoku: "0500",
        chokyoNengappi: "20260620",
        course: null,
        lapTime10f: null,
        lapTime1f: null,
        lapTime2f: null,
        lapTime3f: null,
        lapTime4f: null,
        lapTime5f: null,
        lapTime6f: null,
        lapTime7f: null,
        lapTime8f: null,
        lapTime9f: null,
        timeGokei10f: null,
        timeGokei2f: null,
        timeGokei3f: null,
        timeGokei4f: null,
        timeGokei5f: null,
        timeGokei6f: null,
        timeGokei7f: null,
        timeGokei8f: null,
        timeGokei9f: null,
        tracenKubun: null,
        trainingType: "通常",
        umaban: "5",
      },
    ],
    [
      {
        commentText: null,
        evaluationGrade: "S",
        evaluationText: "気配上昇",
        horseNumber: "5",
        riderName: null,
        trainingDate: "",
      },
    ],
  );
  expect(result).toStrictEqual([
    {
      babamawari: null,
      bamei: "alpha",
      chokyoJikoku: "0500",
      chokyoNengappi: "20260620",
      course: null,
      lapTime10f: null,
      lapTime1f: null,
      lapTime2f: null,
      lapTime3f: null,
      lapTime4f: null,
      lapTime5f: null,
      lapTime6f: null,
      lapTime7f: null,
      lapTime8f: null,
      lapTime9f: null,
      premiumCommentText: null,
      premiumEvaluationGrade: "S",
      premiumEvaluationText: "気配上昇",
      timeGokei10f: null,
      timeGokei2f: null,
      timeGokei3f: null,
      timeGokei4f: null,
      timeGokei5f: null,
      timeGokei6f: null,
      timeGokei7f: null,
      timeGokei8f: null,
      timeGokei9f: null,
      tracenKubun: null,
      trainingRiderName: undefined,
      trainingType: "通常",
      umaban: "5",
    },
  ]);
});

it("attaches a dated review to the latest training row when no row matches the review date", () => {
  const result = mergePremiumTrainingReviews(
    [
      {
        babamawari: null,
        bamei: "alpha",
        chokyoJikoku: "0500",
        chokyoNengappi: "20260615",
        course: null,
        lapTime10f: null,
        lapTime1f: null,
        lapTime2f: null,
        lapTime3f: null,
        lapTime4f: null,
        lapTime5f: null,
        lapTime6f: null,
        lapTime7f: null,
        lapTime8f: null,
        lapTime9f: null,
        timeGokei10f: null,
        timeGokei2f: null,
        timeGokei3f: null,
        timeGokei4f: null,
        timeGokei5f: null,
        timeGokei6f: null,
        timeGokei7f: null,
        timeGokei8f: null,
        timeGokei9f: null,
        tracenKubun: null,
        trainingType: "通常",
        umaban: "5",
      },
      {
        babamawari: null,
        bamei: "alpha",
        chokyoJikoku: "0500",
        chokyoNengappi: "20260620",
        course: null,
        lapTime10f: null,
        lapTime1f: null,
        lapTime2f: null,
        lapTime3f: null,
        lapTime4f: null,
        lapTime5f: null,
        lapTime6f: null,
        lapTime7f: null,
        lapTime8f: null,
        lapTime9f: null,
        timeGokei10f: null,
        timeGokei2f: null,
        timeGokei3f: null,
        timeGokei4f: null,
        timeGokei5f: null,
        timeGokei6f: null,
        timeGokei7f: null,
        timeGokei8f: null,
        timeGokei9f: null,
        tracenKubun: null,
        trainingType: "通常",
        umaban: "5",
      },
    ],
    [
      {
        commentText: "comment-late",
        evaluationGrade: "B",
        evaluationText: "素軽さ出",
        horseNumber: "5",
        riderName: null,
        trainingDate: "2026/06/19",
      },
    ],
  );
  expect(result).toStrictEqual([
    {
      babamawari: null,
      bamei: "alpha",
      chokyoJikoku: "0500",
      chokyoNengappi: "20260615",
      course: null,
      lapTime10f: null,
      lapTime1f: null,
      lapTime2f: null,
      lapTime3f: null,
      lapTime4f: null,
      lapTime5f: null,
      lapTime6f: null,
      lapTime7f: null,
      lapTime8f: null,
      lapTime9f: null,
      timeGokei10f: null,
      timeGokei2f: null,
      timeGokei3f: null,
      timeGokei4f: null,
      timeGokei5f: null,
      timeGokei6f: null,
      timeGokei7f: null,
      timeGokei8f: null,
      timeGokei9f: null,
      tracenKubun: null,
      trainingType: "通常",
      umaban: "5",
    },
    {
      babamawari: null,
      bamei: "alpha",
      chokyoJikoku: "0500",
      chokyoNengappi: "20260620",
      course: null,
      lapTime10f: null,
      lapTime1f: null,
      lapTime2f: null,
      lapTime3f: null,
      lapTime4f: null,
      lapTime5f: null,
      lapTime6f: null,
      lapTime7f: null,
      lapTime8f: null,
      lapTime9f: null,
      premiumCommentText: "comment-late",
      premiumEvaluationGrade: "B",
      premiumEvaluationText: "素軽さ出",
      timeGokei10f: null,
      timeGokei2f: null,
      timeGokei3f: null,
      timeGokei4f: null,
      timeGokei5f: null,
      timeGokei6f: null,
      timeGokei7f: null,
      timeGokei8f: null,
      timeGokei9f: null,
      tracenKubun: null,
      trainingRiderName: undefined,
      trainingType: "通常",
      umaban: "5",
    },
  ]);
});

it("attaches the latest dated review only to the latest training row of three", () => {
  const result = mergePremiumTrainingReviews(
    [
      {
        babamawari: null,
        bamei: "alpha",
        chokyoJikoku: "0500",
        chokyoNengappi: "20260605",
        course: null,
        lapTime10f: null,
        lapTime1f: null,
        lapTime2f: null,
        lapTime3f: null,
        lapTime4f: null,
        lapTime5f: null,
        lapTime6f: null,
        lapTime7f: null,
        lapTime8f: null,
        lapTime9f: null,
        timeGokei10f: null,
        timeGokei2f: null,
        timeGokei3f: null,
        timeGokei4f: null,
        timeGokei5f: null,
        timeGokei6f: null,
        timeGokei7f: null,
        timeGokei8f: null,
        timeGokei9f: null,
        tracenKubun: null,
        trainingType: "通常",
        umaban: "5",
      },
      {
        babamawari: null,
        bamei: "alpha",
        chokyoJikoku: "0500",
        chokyoNengappi: "20260615",
        course: null,
        lapTime10f: null,
        lapTime1f: null,
        lapTime2f: null,
        lapTime3f: null,
        lapTime4f: null,
        lapTime5f: null,
        lapTime6f: null,
        lapTime7f: null,
        lapTime8f: null,
        lapTime9f: null,
        timeGokei10f: null,
        timeGokei2f: null,
        timeGokei3f: null,
        timeGokei4f: null,
        timeGokei5f: null,
        timeGokei6f: null,
        timeGokei7f: null,
        timeGokei8f: null,
        timeGokei9f: null,
        tracenKubun: null,
        trainingType: "通常",
        umaban: "5",
      },
      {
        babamawari: null,
        bamei: "alpha",
        chokyoJikoku: "0500",
        chokyoNengappi: "20260620",
        course: null,
        lapTime10f: null,
        lapTime1f: null,
        lapTime2f: null,
        lapTime3f: null,
        lapTime4f: null,
        lapTime5f: null,
        lapTime6f: null,
        lapTime7f: null,
        lapTime8f: null,
        lapTime9f: null,
        timeGokei10f: null,
        timeGokei2f: null,
        timeGokei3f: null,
        timeGokei4f: null,
        timeGokei5f: null,
        timeGokei6f: null,
        timeGokei7f: null,
        timeGokei8f: null,
        timeGokei9f: null,
        tracenKubun: null,
        trainingType: "通常",
        umaban: "5",
      },
    ],
    [
      {
        commentText: "comment-older",
        evaluationGrade: "C",
        evaluationText: "older",
        horseNumber: "5",
        riderName: null,
        trainingDate: "2026/06/10",
      },
      {
        commentText: "comment-latest",
        evaluationGrade: "B",
        evaluationText: "素軽さ出",
        horseNumber: "5",
        riderName: null,
        trainingDate: "2026/06/19",
      },
    ],
  );
  expect(result).toStrictEqual([
    {
      babamawari: null,
      bamei: "alpha",
      chokyoJikoku: "0500",
      chokyoNengappi: "20260605",
      course: null,
      lapTime10f: null,
      lapTime1f: null,
      lapTime2f: null,
      lapTime3f: null,
      lapTime4f: null,
      lapTime5f: null,
      lapTime6f: null,
      lapTime7f: null,
      lapTime8f: null,
      lapTime9f: null,
      timeGokei10f: null,
      timeGokei2f: null,
      timeGokei3f: null,
      timeGokei4f: null,
      timeGokei5f: null,
      timeGokei6f: null,
      timeGokei7f: null,
      timeGokei8f: null,
      timeGokei9f: null,
      tracenKubun: null,
      trainingType: "通常",
      umaban: "5",
    },
    {
      babamawari: null,
      bamei: "alpha",
      chokyoJikoku: "0500",
      chokyoNengappi: "20260615",
      course: null,
      lapTime10f: null,
      lapTime1f: null,
      lapTime2f: null,
      lapTime3f: null,
      lapTime4f: null,
      lapTime5f: null,
      lapTime6f: null,
      lapTime7f: null,
      lapTime8f: null,
      lapTime9f: null,
      timeGokei10f: null,
      timeGokei2f: null,
      timeGokei3f: null,
      timeGokei4f: null,
      timeGokei5f: null,
      timeGokei6f: null,
      timeGokei7f: null,
      timeGokei8f: null,
      timeGokei9f: null,
      tracenKubun: null,
      trainingType: "通常",
      umaban: "5",
    },
    {
      babamawari: null,
      bamei: "alpha",
      chokyoJikoku: "0500",
      chokyoNengappi: "20260620",
      course: null,
      lapTime10f: null,
      lapTime1f: null,
      lapTime2f: null,
      lapTime3f: null,
      lapTime4f: null,
      lapTime5f: null,
      lapTime6f: null,
      lapTime7f: null,
      lapTime8f: null,
      lapTime9f: null,
      premiumCommentText: "comment-latest",
      premiumEvaluationGrade: "B",
      premiumEvaluationText: "素軽さ出",
      timeGokei10f: null,
      timeGokei2f: null,
      timeGokei3f: null,
      timeGokei4f: null,
      timeGokei5f: null,
      timeGokei6f: null,
      timeGokei7f: null,
      timeGokei8f: null,
      timeGokei9f: null,
      tracenKubun: null,
      trainingRiderName: undefined,
      trainingType: "通常",
      umaban: "5",
    },
  ]);
});

it("leaves trainings without umaban unchanged", () => {
  const result = mergePremiumTrainingReviews(
    [
      {
        babamawari: null,
        bamei: "alpha",
        chokyoJikoku: "0500",
        chokyoNengappi: "20260620",
        course: null,
        lapTime10f: null,
        lapTime1f: null,
        lapTime2f: null,
        lapTime3f: null,
        lapTime4f: null,
        lapTime5f: null,
        lapTime6f: null,
        lapTime7f: null,
        lapTime8f: null,
        lapTime9f: null,
        timeGokei10f: null,
        timeGokei2f: null,
        timeGokei3f: null,
        timeGokei4f: null,
        timeGokei5f: null,
        timeGokei6f: null,
        timeGokei7f: null,
        timeGokei8f: null,
        timeGokei9f: null,
        tracenKubun: null,
        trainingType: "通常",
        umaban: null,
      },
    ],
    [
      {
        commentText: "comment-x",
        evaluationGrade: "B",
        evaluationText: "目立たず",
        horseNumber: "5",
        riderName: null,
        trainingDate: "2026/06/20",
      },
    ],
  );
  expect(result).toStrictEqual([
    {
      babamawari: null,
      bamei: "alpha",
      chokyoJikoku: "0500",
      chokyoNengappi: "20260620",
      course: null,
      lapTime10f: null,
      lapTime1f: null,
      lapTime2f: null,
      lapTime3f: null,
      lapTime4f: null,
      lapTime5f: null,
      lapTime6f: null,
      lapTime7f: null,
      lapTime8f: null,
      lapTime9f: null,
      timeGokei10f: null,
      timeGokei2f: null,
      timeGokei3f: null,
      timeGokei4f: null,
      timeGokei5f: null,
      timeGokei6f: null,
      timeGokei7f: null,
      timeGokei8f: null,
      timeGokei9f: null,
      tracenKubun: null,
      trainingType: "通常",
      umaban: null,
    },
  ]);
});

it("preserves trainingRiderName from review when provided", () => {
  const result = mergePremiumTrainingReviews(
    [
      {
        babamawari: null,
        bamei: "alpha",
        chokyoJikoku: "0500",
        chokyoNengappi: "20260620",
        course: null,
        lapTime10f: null,
        lapTime1f: null,
        lapTime2f: null,
        lapTime3f: null,
        lapTime4f: null,
        lapTime5f: null,
        lapTime6f: null,
        lapTime7f: null,
        lapTime8f: null,
        lapTime9f: null,
        timeGokei10f: null,
        timeGokei2f: null,
        timeGokei3f: null,
        timeGokei4f: null,
        timeGokei5f: null,
        timeGokei6f: null,
        timeGokei7f: null,
        timeGokei8f: null,
        timeGokei9f: null,
        tracenKubun: null,
        trainingType: "通常",
        umaban: "5",
      },
    ],
    [
      {
        commentText: null,
        evaluationGrade: "S",
        evaluationText: "気配上昇",
        horseNumber: "5",
        riderName: "rider-z",
        trainingDate: "2026/06/20",
      },
    ],
  );
  expect(result).toStrictEqual([
    {
      babamawari: null,
      bamei: "alpha",
      chokyoJikoku: "0500",
      chokyoNengappi: "20260620",
      course: null,
      lapTime10f: null,
      lapTime1f: null,
      lapTime2f: null,
      lapTime3f: null,
      lapTime4f: null,
      lapTime5f: null,
      lapTime6f: null,
      lapTime7f: null,
      lapTime8f: null,
      lapTime9f: null,
      premiumCommentText: null,
      premiumEvaluationGrade: "S",
      premiumEvaluationText: "気配上昇",
      timeGokei10f: null,
      timeGokei2f: null,
      timeGokei3f: null,
      timeGokei4f: null,
      timeGokei5f: null,
      timeGokei6f: null,
      timeGokei7f: null,
      timeGokei8f: null,
      timeGokei9f: null,
      tracenKubun: null,
      trainingRiderName: "rider-z",
      trainingType: "通常",
      umaban: "5",
    },
  ]);
});
